packages:
  # - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-nextjs": ^0.12.0
  "@types/node": ^22.13.0

  "@trpc/client": &trpc ^11.0.0-rc.730
  "@trpc/react-query": *trpc
  "@trpc/server": *trpc

  "@arcjet/next": &arcjet ^1.0.0-beta.1
  "@arcjet/decorate": *arcjet

  tailwindcss: &tailwind ^4.0.2
  "@tailwindcss/postcss": *tailwind

  eslint: ^9.19.0
  prettier: ^3.4.2
  typescript: ^5.7.3
  zod: ^3.24.1

catalogs:
  next:
    next: &next ^15.1.6
    "@next/eslint-plugin-next": *next
    "@next/bundle-analyzer": *next

  react19:
    react: &react ^19.0.0
    react-dom: *react
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3
