packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-nextjs": ^0.12.0
  "@types/node": ^22.13.1

  "@trpc/client": ^11.0.0-rc.761
  "@trpc/react-query": ^11.0.0-rc.761
  "@trpc/server": ^11.0.0-rc.761

  "@arcjet/next": ^1.0.0-beta.2
  "@arcjet/decorate": ^1.0.0-beta.2

  tailwindcss: ^4.0.6
  "@tailwindcss/postcss": ^4.0.6

  eslint: ^9.20.1
  prettier: ^3.5.0
  typescript: ^5.7.3
  zod: ^3.24.1

catalogs:
  next:
    next: ^15.1.7
    "@next/eslint-plugin-next": ^15.1.7
    "@next/bundle-analyzer": ^15.1.7

  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.8
    "@types/react-dom": ^19.0.3
