packages:
  # - apps/*
  - packages/*
  - tooling/*

catalog:
  "@t3-oss/env-nextjs": ^0.11.1
  "@types/node": ^22.10.5

  "@arcjet/next": &arcjet ^1.0.0-alpha.34
  "@arcjet/decorate": *arcjet

  eslint: ^9.17.0
  prettier: ^3.4.2
  typescript: ^5.7.2
  zod: ^3.24.1

catalogs:
  react19:
    react: &react ^19.0.0
    react-dom: *react
    "@types/react": &react-types ^19.0.2
    "@types/react-dom": *react-types
